---
title: "Povijest promjena na stranici"
---

30.07.2026.

- 19:53 objavljena poglavlja [3.4](integrali/integrali-racionalne.qmd), [3.5](integrali/integrali-iracionalne.qmd), [3.6](integrali/integrali-trig.qmd) i [drugi dio zadataka iz integrala](integrali/integrali-zadatci2.qmd).

---

10.07.2026.

- 16:45 objavljena rješenja trećeg dijela zadataka iz poglavlja o derivacijama ([Zadatci 3](derivacije/derivacije-zadatci3.qmd)). Dodana cjelina [3. Riemannov integral](integrali/integrali.qmd) i prva poglavlja sa [zadatcima](integrali/integrali-zadatci1.qmd)

---

09.07.2026.

- 06:40 objavljena rješenja drugog dijela zadataka iz poglavlja o derivacijama ([Zadatci 2](derivacije/derivacije-zadaci2.qmd)) i dodan treći dio derivacija

---

05.07.2026.

- 18:00 ispravljen dokaz Lagrangeovog teorema srednje vrijednosti u poglavlju [2.4](derivacije/derivacije-rezultati.qmd)

---

04.07.2026.

- 21:40 dodana poglavlja [2.4](derivacije/derivacije-rezultati.qmd) i [2.5](derivacije/derivacije-tok.qmd) i drugi dio [zadataka](derivacije/derivacije-zadaci2.qmd) iz derivacija

- 15:56 objavljena rješenja prvog dijela zadataka iz poglavlja o derivacijama ([Zadatci 1](derivacije/derivacije-zadaci1.qmd))

---

02.07.2026.

- 08:16 objavljena rješenja zadataka iz poglavlja o limesima ([Zadatci](limesi/limesi-zadatci.qmd))

---

01.07.2026.

- 11:00 dodano poglavlje o limesima i neprekidnosti

- 08:00 dodano poglavlje o derivacijama i diferencijabilnosti

---

30.06.2026. 

- stranica stvorena