# Zadatci {.unnumbered}

:::{.zadatak}
Koristeći L'Hospitalovo pravilo izračunajte sljedeće limese:

(a) $\displaystyle \lim_{x \to 0} \dfrac{e^x-x-1}{\cos x -1}$

(b) $\displaystyle \lim_{x \to -2} \dfrac{x^3-x^2-10x-8}{5x^3+12x^2-2x-12}$

(c) $\displaystyle \lim_{x \to a} \dfrac{x-a}{\ln x - \ln a}, \; a \in \langle 0, +\infty \rangle$

(d) $\displaystyle \lim_{x \to 0} \dfrac{1-\cos x}{x^2}$
:::

<!--
:::{.rjesenje}
<details>
<summary>Prikaži rješenje</summary>

(a) 
$$
\lim_{x \to 0} \dfrac{e^x-x-1}{\cos x -1} = \left [ \dfrac{0}{0}\right ] \overset{L'H}{=}
\lim_{x \to 0} \dfrac{e^x-1}{-\sin x } = \left [ \dfrac{0}{0}\right ] \overset{L'H}{=}
-\lim_{x \to 0} \dfrac{e^x}{\cos x} = -1
$$

(b)
$$
\lim_{x \to -2} \dfrac{x^3-x^2-10x-8}{5x^3+12x^2-2x-12} = \left [ \dfrac{0}{0}\right ] \overset{L'H}{=}
\lim_{x \to -2} \dfrac{3x^2-2x-10}{15x^2+24x-2} = \dfrac{6}{10} = \dfrac{3}{5}
$$

(c)
$$ 
\lim_{x \to a} \dfrac{x-a}{\ln x - \ln a} = \left [ \dfrac{0}{0}\right ] \overset{L'H}{=}
\lim_{x \to a} \dfrac{1}{\dfrac{1}{x}} = a
$$

(d)
$$
\lim_{x \to 0} \dfrac{1-\cos x}{x^2} = \left [ \dfrac{0}{0}\right ] \overset{L'H}{=}
\lim_{x \to 0} \dfrac{\sin x}{2x} = \left [ \dfrac{0}{0}\right ] \overset{L'H}{=}
\lim_{x \to 0} \dfrac{\cos x}{2} = \dfrac{1}{2}
$$

</details>
:::
-->

---

:::{.zadatak}
Ispitajte tok funkcije $f(x) = \sqrt{8+x} - \sqrt{8-x}$ i skicirajte njezin graf.
:::

<!--
:::{.rjesenje}
<details>
<summary>Prikaži rješenje</summary>

**1. Domena** | Imamo uvjete
$$
8+x \geq 0 \quad 8-x \geq 0 \qquad \Rightarrow x \in [-8,8] = D_f
$$

---

**2. Parnost, neparnost i periodičnost** | Ispitajmo (ne)parnost:
$$
\displaystyle f(-x) = \sqrt{8-x} - \sqrt{8+x} = - (\sqrt{8+x} - \sqrt{8-x}) = -f(x)
$$

Funkcija je neparna.

---

**3. Neprekidnost** | Funkcija je kompozicija elementarnih funkcija pa zaključujemo da je neprekidna na cijeloj domeni.

---

**4. Nultočke** | Vrijedi
$$
\begin{align*}
\sqrt{8+x} - \sqrt{8-x} &= 0 \\
\sqrt{8+x} &= \sqrt{8-x} \\
8+x &= 8-x \\
x &= 0
\end{align*}
$$

pa je $x_0 = 0$ nultočka.

---

**5. Monotonost i lokalni ekstremi** | Računamo $f'$ i $f''$:
$$
\displaystyle f'(x) = \frac{1}{2\sqrt{8+x}}+\frac{1}{2\sqrt{8-x}} \qquad 
f''(x) = \frac{1}{4(8-x)^{3/2}} -\frac{1}{4(8+x)^{3/2}}
$$

Pripazimo kod računanja derivacije kompozicije jer je $(\sqrt{8-x})' = \dfrac{-1}{2\sqrt{8-x}}$. Uočimo da je prva derivacija uvijek veća od $0$ pa nema nultočku. Također, zbog toga je funkcija $f$ strogo rastuća na cijelom $[-8,8]$. Tada su jedine kritične točke ove funkcije upravo rubovi domene, tj. $-8$ i $8$. 

Budući da je $f$ strogo rastuća, minimum je u lijevom, a maksimum u desnom rubu i oni iznose $-4$ i $4$, respektivno.

Uočimo da se radi o globalnim ekstremima!

---

**6. Koveksnost, konkavnost i točke infleksije** | Uočimo da je $f''(x) = 0$ samo za $x=0$ pa je to točka infleksije. Provjerom vidimo da je za $x < 0$ funkcija konkavna jer je $f''(x) < 0$, a za $x>0$ je funkcija koveksna.

---

**7. Asimptote** | Kako je funkcija definirana na segmentu $[-8,8]$ nema smisla tražiti kose ili horizontalne asimptote jer njih ispitujemo za argument $x \to \infty$ što nije moguće. Isto tako, vertikalne asimptote tražimo u rubovima domene, što su $x = \pm 8$, ali ondje funkcija postiže konkretne vrijednosti pa ni tamo nema asimptote.

---

**8. Graf** Tablica:

| $x$ | $-8$ | $\longrightarrow$ | $0$ | $\longrightarrow$ | $8$ |
|:--:|:--:|:-----------------:|:---:|:-----------------:|:---:|
| $f'(x)$ | | $+$ | | $+$ | |
| $f''(x)$ |  | $-$  | | $+$ | | 
| $f(x)$ | | $-\nearrow \cap$  | | $+\nearrow \cup$ | |

Promatramo intervala između točaka koje su nam bile bi tne (nultočke derivacija) i ispod pišemo predznake prve i druge derivacije. Iz njih iščitavamo pad i raste od $f$ te intervale konveksnosti. Ispod rubnih točaka ništa ne pišemo.

Graf:

```{python}
#| echo: true
#| output: true
#| code-fold: true
#| code-summary: "Prikaži Python kod"
#| fig-align: center

import numpy as np
import matplotlib.pyplot as plt

def f(x):
    return np.sqrt(8+x) - np.sqrt(8-x)

x = np.linspace(-8, 8, 2000)

x0 = 0

fig, ax = plt.subplots(figsize=(8,5))

ax.plot(x, f(x), color="blue", linewidth=2)

# osi
ax.axhline(0, linewidth=1)
ax.axvline(0, linewidth=1)

# točke
ax.scatter(x0, f(x0), zorder=5)

ax.text(x0+0.4, f(x0)-0.5, "f(x0)")

ax.set_xlim(-10, 10)
ax.set_ylim(-6, 6)

ax.annotate('', xy=(10, 0), xytext=(-10, 0),
            arrowprops=dict(arrowstyle='->', linewidth=1.2, color='black'))

ax.annotate('', xy=(0, 6), xytext=(0, -6),
            arrowprops=dict(arrowstyle='->', linewidth=1.2, color='black'))

ax.grid(True, linestyle="--",linewidth=0.5, alpha=0.5)
plt.show()
```

</details>
:::
-->

---

:::{.zadatak}
Ispitajte tok funkcije $f(x) = xe^x$ i skicirajte njezin graf.a
:::

<!--
:::{.rjesenje}
<details>
<summary>Prikaži rješenje</summary>

**1. Domena** | $D_f = \mathbb{R}$.

---

**2. Parnost, neparnost i periodičnost** | Odmah uočavamo da $f$ nije ni parna ni neparna.

---

**3. Neprekidnost** | Funkcija je kompozicija elementarnih funkcija pa zaključujemo da je neprekidna na cijeloj domeni.

---

**4. Nultočke** | $f(x)=0$ samo za $x_0 = 0$.

---

**5. Monotonost i lokalni ekstremi** | Računamo $f'$ i $f''$:
$$
f'(x) = (1+x)e^x \qquad f''(x) = (2+x)e^x
$$

Stacionarna točka je $x_1 = -1$. Ispitajmo karakter:
$$
f''(-1) = 2e^{-1} > 0
$$

pa $f$ ima lokalni minimum u $x=-1$ i iznosi $-e^{-1}$.

---

**6. Koveksnost, konkavnost i točke infleksije** | Nultočka od $f''(x)$ je $x_2 = -2$ pa je to točka infleksije. Za $x<2$ je $f''(x)<0$ pa je funkcija konkavna, a za $x>2$ je funkcija konveksna.

---

**7. Asimptote** | Vertikalnih asimptota nema. Za kose i horizontalne ispitajmo limese:
$$
\lim_{x \to \infty} \dfrac{f(x)}{x} = \infty
$$

pa u pozitivnoj grani nema kosih ni horizontalnih asimptota.
$$
\lim_{x \to -\infty} \dfrac{f(x)}{x} = 0 = k
$$

$$
\lim_{x \to -\infty} f(x) - kx = 0
$$

pa je horizontalna asimptota u negativnoj grani $y=0$.


---

**8. Graf** Tablica:

| $x$ | $-\infty$ | $\longrightarrow$ | $x_2$ | $\longrightarrow$ | $x_1$ | $\longrightarrow$ | $x_0$ | $\longrightarrow$ | $+\infty$ |
|:---:|:---------:|:-----------------:|:----:|:-----------------:|:-----:|:-----------------:|:-----:|:-----------------:|:-----:|
| $f'(x)$ | | $-$ | | $-$ | | $+$ | | $+$ | |
| $f''(x)$ | | $-$ | | $+$ | | $+$ | | $+$ | |
| $f(x)$ | | $-\searrow \cap$ | | $-\searrow \cup$ | | $-\nearrow \cup$ | | $+\nearrow \cup$ | |

Graf:

```{python}
#| echo: true
#| output: true
#| code-fold: true
#| code-summary: "Prikaži Python kod"
#| fig-align: center

import numpy as np
import matplotlib.pyplot as plt

def f(x):
    return x*np.exp(x)

x = np.linspace(-10, 10, 2000)

x0 = 0
x1 = -1
x2 = -2

fig, ax = plt.subplots(figsize=(8,5))

ax.plot(x, f(x), color="blue", linewidth=2)

# asimptote
ax.plot([-10, 0], [0, 0], linewidth=3.2, color="orange", linestyle="--")  # y = 0, lijevo

#natpisi asimptota
ax.text(-3.5, 0.2, "y = 0", fontsize=10)

# osi
ax.axhline(0, linewidth=1)
ax.axvline(0, linewidth=1)

# točke
ax.scatter([x0, x1, x2],
            [f(x0), f(x1), f(x2)],
            zorder=5)

ax.text(x0+0.2, f(x0)-0.3, "f(x0)")
ax.text(x1-0.1, f(x1)-0.3, "f(x1)")
ax.text(x2-0.1, f(x2)-0.3, "f(x2)")

ax.set_xlim(-6, 3)
ax.set_ylim(-1.5, 4)

ax.annotate('', xy=(3, 0), xytext=(-6, 0),
            arrowprops=dict(arrowstyle='->', linewidth=1.2, color='black'))

ax.annotate('', xy=(0, 4), xytext=(0, -1.5),
            arrowprops=dict(arrowstyle='->', linewidth=1.2, color='black'))

ax.grid(True, linestyle="--",linewidth=0.5, alpha=0.5)
plt.show()
```

</details>
:::
-->

---

:::{.zadatak}
Ispitajte tok funkcije $f(x) = \dfrac{1 - \ln x}{1 + \ln x}$ i skicirajte njezin graf.
:::

:::{.hint}
<details>
<summary>Prikaži hint</summary>
Domena logaritma je $\langle 0, +\infty \rangle$ i vrijedi $\log _a a = 1, \; \forall a \in \mathbb{R}^+$.
</details>
:::

<!--
:::{.rjesenje}
<details>
<summary>Prikaži rješenje</summary>

**1. Domena** | Imamo uvjet $x > 0$ i $1 + \ln x \neq 0$ što je zadovoljeno za $x \neq e^{-1}$. Dakle domena je $D_f = \langle 0, \infty \rangle \backslash \{e^{-1} \}$.

---

**2. Parnost, neparnost i periodičnost** | Vidimo da ne treba provjeravati ova svojstva zbog domene (ako je $a \in D_f$, onda $-a \notin D_f$).

---

**3. Neprekidnost** | Funkcija ima prekid druge vrste u točki $x_0 = e^{-1}$ pa će ondje imati vertikalnu asimptotu.

---

**4. Nultočke** | $f(x)=0$ ako je $1-\ln x = 0$, tj. za $x_1 = e$.

---

**5. Monotonost i lokalni ekstremi** | Računamo $f'$ i $f''$:
$$
f'(x) = -\dfrac{2}{x(1+\ln x)^2} \qquad f''(x) = \dfrac{2(3+\ln x)}{x^2(\ln x + 1)^3}
$$

Funkcija $f$ nema stacionarnih točaka pa promatramo skup kritičnih točaka $\{0,e^{-1}\}$. Budući da $f$ ima prekid druge vrste u $e^{-1}$, to nije kandidat za ekstrem. Jednako tako, funkcija nije definirana u $0$ pa ni tamo ne može postići ekstrem.

Dodatno, uočimo da je $f'(x) < 0$ na cijeloj domeni pa je $f$ strogo padajuća.

---

**6. Koveksnost, konkavnost i točke infleksije** | Odredimo točku infleksije: $f''(x) = 0$ ako je $3+\ln x = 0$ pa $f$ ima točku infleksije u $x_2 = e^{-3}$. Za $x<e^{-3}$ je $f''(x)>0$ pa je funkcija konveksa, a za $x\in \langle e^{-3}, e^{-1}\rangle$ je funkcija konkavna. Zatim nakon prekida funkcije $f$ u točki $e^{-1}$ opet imamo $f''(x) > 0$ pa je funkcija konveksna.

---

**7. Asimptote** | Imamo vertikalnu asimptotu $x = e^{-1}$. Provjerimo funkciju oko te asimptote promatrajući lijevi i desni limes:

$$
\lim_{x \to e^{-1}-} f(x) = \lim_{x \to e^{-1}-} \dfrac{1 - \ln x}{1 + \ln x}
$$

Uočimo da je tada brojnik $>2$, a nazivnik teži u $0^-$, dakle limes je jednak $- \infty$.

Analogno dobijemo $\displaystyle \lim_{x \to e^{-1}+} f(x) = \infty$.

Ispitajmo kose i horizontalne asimptote:
$$
\lim_{x \to \infty} \dfrac{f(x)}{x} = 0 = k
$$

$$
\lim_{x \to \infty} f(x) = -1
$$

pa je $y = -1$ horizontalna asimptota.

Ispitajmo još ponašanje blizu $x = 0$. Tvrdimo da ondje nemamo vertikalnu asimptotu. Imamo limes
$$
\lim_{x \to 0+} f(x) = \lim_{x \to 0+} \dfrac{1 - \ln x}{1 + \ln x} \overset{L'H}{=} \lim_{x \to 0+} \frac{-\dfrac{1}{x}}{\dfrac{1}{x}} = -1
$$

Dakle, funkcija *kreće* od $-1$, a zatim strogo pada. Dakle, ondje nema vertikalnu asimptotu.

---

**8. Graf** Tablica:

| $x$ | $0$ | $\longrightarrow$ | $x_2$ | $\longrightarrow$ | $x_0$ | $\longrightarrow$ | $x_1$ | $\longrightarrow$ | $+\infty$ |
|:---:|:---------:|:-----------------:|:----:|:-----------------:|:-----:|:-----------------:|:-----:|:-----------------:|:-----:|
| $f'(x)$ | | $-$ | | $-$ | | $-$ | | $-$ | |
| $f''(x)$ | | $+$ | | $-$ | | $+$ | | $+$ | |
| $f(x)$ | | $-\searrow \cup$ | | $-\searrow \cap$ | | $+\searrow \cup$ | | $-\searrow \cup$ | |

Graf:

```{python}
#| echo: true
#| output: true
#| code-fold: true
#| code-summary: "Prikaži Python kod"
#| fig-align: center

import numpy as np
import matplotlib.pyplot as plt

def f(x):
    return (1-np.log(x))/(1+np.log(x))

y1 = np.linspace(np.exp(-9), np.exp(-1)-np.exp(-6), 2000)
y2 = np.linspace(np.exp(-1)+np.exp(-6), 8, 2000)


x0 = np.exp(-1)
x1 = np.exp(1)
x2 = np.exp(-2)

fig, ax = plt.subplots(figsize=(8,5))

ax.plot(y1, f(y1), color="blue", linewidth=2)
ax.plot(y2, f(y2), color="blue", linewidth=2)

# asimptote
ax.plot([0, 10], [-1, -1], color="orange", linestyle="--")  # y = 0, lijevo
ax.axvline(np.exp(-1), color='orange', linestyle="--")

#natpisi asimptota
ax.text(4, -1.4, "y = -1", fontsize=10)
ax.text(np.exp(-1)+0.1, -2, "x = e^-1", fontsize=10)

# osi
ax.axhline(0, linewidth=1)
ax.axvline(0, linewidth=1)

# točke
ax.scatter([x1, x2],
            [f(x1), f(x2)],
            zorder=5)

ax.text(x1-0.1, f(x1)-0.45, "f(x1)")
ax.text(x2+0.3, f(x2)-0.3, "f(x2)")

ax.set_xlim(0, 8)
ax.set_ylim(-5, 5)

ax.annotate('', xy=(8, 0), xytext=(0, 0),
            arrowprops=dict(arrowstyle='->', linewidth=1.2, color='black'))

ax.annotate('', xy=(0, 5), xytext=(0, -5),
            arrowprops=dict(arrowstyle='->', linewidth=1.2, color='black'))

ax.grid(True, linestyle="--",linewidth=0.5, alpha=0.5)
plt.show()
```

</summary>
:::
-->

---

:::{.zadatak}
**(napredno)** Koliko najviše nultočaka može imati strogo konveksna funkcija?
:::

:::{.hint}
<details>
<summary>Prikaži hint</summary>
Pokušajte pronaći neku konveksnu funkciju i prebrojite joj nultočke, a zatim pretpostavite da ih postoji više. Tada u jednom trenutku trebate dobiti Jensenovu (strogu) nejednakost.
</details>
:::

<!--
:::{.rjesenje}
<details>
<summary>Prikaži rješenje</summary>

Neka je $f$ strogo konveksna funkcija. Primjerice, $f(x) = x^2 - 4$ je konveksna funkcija. Uočimo da ona ima dvije nultočke, $x_{1,2} = \pm 2$. Dokažimo da svaka strogo konveksna funkcija ima najviše dvije nultočke.

Pretpostavimo da neka konveksna funkcija $f$ ima nultočke $x_1,x_2$ i $x_3$ takve da je $x_1 < x_2 < x_3$. Budući da je $x_2$ između ostalih dviju nultočki, možemo ju prikazati kao konveksnu kombinaciju točaka $x_1$ i $x_3$, tj. $\exists t \in [0,1]$ takav da je
$$
x_2 = (1-t)x_1 + tx_3
$$

Kako je $f$ strogo konveksna vrijedi 
$$
f((1-t)x_1 + tx_3) < (1-t)f(x_1) + tf(x_3) 
$$

Odnosno, dobijemo
$$
0 = f(x_2) = f((1-t)x_1 + tx_3) < (1-t)f(x_1) + tf(x_3) 0
$$

što je očito kontradikcija. Dakle, strogo konveksne funkcije imaju najviše $2$ nultočke.

</details>
:::
-->