# Zadatci {.unnumbered}

:::{.zadatak}
Odredite sljedeće integrale metodom supstitucije:

(a) $\displaystyle \int (3x^2-2x+1)(x^3-x^2+x-9)^7 \, dx$

(b) $\displaystyle \int \frac{e^x+1}{e^x+x} \, dx$

(c) $\displaystyle \int _e^{e^e} x^3e^{x^4} \, dx$

(d) $\displaystyle \int _0^4 x \sqrt{x^2 + 9} \, dx$

(e) $\displaystyle \int \frac{\cos \sqrt{x}}{\sqrt{x}} \, dx$

(f) $\displaystyle \int \frac{x}{\sqrt{x+1}} \, dx$
:::

:::{.hint}
<details>
<summary>Prikaži hint</summary>
U *f.* dijelu iskoristite supstituciju $t = \sqrt{x+1}$, a zatim zapišite kao $t^2 = x+1$. Tada je puno lakše pronaći odgovarajući izraz za $dt$, ali pazite, pri derivaciji lijeve strane morate primijeniti pravilo za kompoziciju pa dobijete $2t \, dt$, tj. derivacija vanjske funkcije puta derivacija unutarnje, što je $dt$. To se zove implicitno deriviranje.
</details>
:::

:::{.rjesenje}
<details>
<summary>Prikaži rješenje</summary>
(a)
$$
\begin{align*}
\int (3x^2-2x+1)&(x^3-x^2+x-9)^7 \, dx =
\left | 
\begin{aligned}
t &= x^3-x^2+x-9 \\
dt &= (3x^2 - 2x +1) \,dx
\end{aligned}
\right | \\ 
&= \int t^7 \, dt = \frac{t^8}{8} + C = \frac{(x^3-x^2+x-9)^8}{8} + C, \ C \in \mathbb{R}
\end{align*}
$$

(b)
$$
\int \frac{e^x+1}{e^x+x} \, dx =
\left | 
\begin{aligned}
t &= e^x+x \\
dt &= (e^x+1) \,dx
\end{aligned}
\right |= 
\int \frac{dt}{t} = \ln |t| + C = \ln |e^x+x| + C, \ C \in \mathbb{R}
$$

(c)
$$
\int _e^{e^e} x^3e^{x^4} \, dx =
\left | 
\begin{aligned}
t &= x^4 & e &\mapsto e^4 \\
dt &= 4x^3 \,dx & e^e &\mapsto e^{4e}
\end{aligned}
\right |= 
\dfrac{1}{4}\int _{e^4}^{e^{4e}} e^t \, dt = \frac{1}{4}\left(e^{e^{4e}} - e^{e^4} \right)
$$

(d)
$$
\int _0^4 x \sqrt{x^2 + 9} \, dx =
\left | 
\begin{aligned}
t &= x^2 + 9 & 0 &\mapsto 9 \\
dt &= 2x \,dx & 4 &\mapsto 25
\end{aligned}
\right |= 
\frac{1}{2}\int _9^{25} \sqrt{t} \, dt = \frac{1}{2}\left(\frac{t^\frac{3}{2}}{\frac{3}{2}} \right) \Big|_9^{25} = \frac{98}{3}
$$

(e)
$$
\int \frac{\cos \sqrt{x}}{\sqrt{x}} \, dx =
\left | 
\begin{aligned}
t &= \sqrt{x} \\
dt &= \frac{1}{2\sqrt{x}} \,dx
\end{aligned}
\right |= 
2 \int \cos t \, dt = 2\sin t + C = 2\sin \sqrt{x} + C, \ C \in \mathbb{R}
$$

(f)
$$
\begin{align*}
\int \frac{x}{\sqrt{x+1}} \, dx =
\left | 
\begin{aligned}
t = \sqrt{x+1} &\Rightarrow t^2 = x+1 \\
2t\, dt &= dx
\end{aligned}
\right | &= 
\int \frac{t^2-1}{t}2t \, dt = 2 \int (t^2-1) \, dt \\
= 2 \left (\frac{t^3}{3} - t \right ) + C = 2 &\left (\frac{(x+1)^\frac{3}{2}}{3} - \sqrt{x+1} \right ) + C, \ C \in \mathbb{R}
\end{align*}
$$
</details>
:::

---

:::{.zadatak}
Odredite sljedeće integrale metodom parcijalne integracije:

(a) $\displaystyle \int _0^1 \ln (1+x^2) \, dx$

(b) $\displaystyle \int \ln x \, dx$

(c) $\displaystyle \int \frac{x}{\cos^2 x} \, dx$

(d) $\displaystyle \int 4 x \cos ⁡(2−3⁢𝑥) \, dx$

(e) $\displaystyle \int (x^4 + 3x) \cos x \, dx$ (**napredno**)
:::

:::{.rjesenje}
<details>
<summary>Prikaži rješenje</summary>
(a)
$$
\begin{align*}
\int _0^1 \ln (1+x^2) \, dx &=
\left | 
\begin{aligned}
u &= \ln (1+x^2) & du &= \frac{2x}{1+x^2}\\
dv &= dx & v &= x
\end{aligned}
\right | \\
&= x\ln (1+x^2) \Big| _0^1 - \int _0^1 \frac{2x^2}{1+x^2}\, dx = \ln 2 - \int _0^1 \left ( 2- \frac{2}{1+x^2} \right )\, dx \\
&= \ln 2 -2x \Big| _0^1 -2 \operatorname{arctg} x \Big| _0^1 = \ln2 - 2 - \frac{\pi}{2}
\end{align*}
$$

(b)
$$
\int \ln x \, dx =
\left | 
\begin{aligned}
u &= \ln x & du &= \frac{dx}{x}\\
dv &= dx & v &= x
\end{aligned}
\right | \\
= x\ln x - \int \, dx = x(\ln x - 1) + C, \ C \in \mathbb{R}
$$

(c)
$$
\int \frac{x}{\cos^2 x} \, dx =
\left | 
\begin{aligned}
u &= x & du &= dx\\
dv &= \frac{dx}{\cos ^2 x } & v &= \operatorname{tg} x
\end{aligned}
\right | \\
= x \operatorname{tg} x - \int \operatorname{tg} x \, dx
$$

Riješimo metodom zamjene varijabli zadnji integral
$$
\int \operatorname{tg} x \, dx = \int \frac{\sin x}{\cos x} \, dx =
\left | 
\begin{aligned}
t &= \cos x \\
dt &= -\sin x \, dx
\end{aligned}
\right | =
- \int \frac{dt}{t} = - \ln |\cos t| + C
$$

Konačno imamo
$$
\int \frac{x}{\cos^2 x} \, dx = x \operatorname{tg} x + \ln |\cos t| + C, \ C \in \mathbb{R}
$$

(d)
$$
\begin{align*}
\int 4x \cos(2-3x)\, dx &=
\left |
\begin{aligned}
u &= 4x & du &= 4\,dx\\
dv &= \cos(2-3x)\,dx & v &= -\frac13\sin(2-3x)
\end{aligned}
\right | \\
&= -\frac{4x}{3}\sin(2-3x) +\frac{4}{3}\int \sin(2-3x)\,dx \\ 
&= -\frac{4x}{3}\sin(2-3x) +\frac{4}{9}\cos(2-3x) + C, \ C \in \mathbb{R}
\end{align*}
$$

(e)
$$
\begin{align*}
\int (x^4+3x)\cos x\,dx
&=
\left|
\begin{aligned}
u &= x^4+3x & du &= (4x^3+3)\,dx\\
dv &= \cos x\,dx & v &= \sin x
\end{aligned}
\right| \\
&= (x^4+3x)\sin x-\int(4x^3+3)\sin x\,dx\\
&= (x^4+3x)\sin x
+\left|
\begin{aligned}
u &= 4x^3+3 & du &= 12x^2\,dx\\
dv &= \sin x\,dx & v &= -\cos x
\end{aligned}
\right| \\
&= (x^4+3x)\sin x +(4x^3+3)\cos x -12\int x^2\cos x\,dx\\
&= (x^4+3x)\sin x +(4x^3+3)\cos x -12\left(
\left|
\begin{aligned}
u &= x^2 & du &= 2x\,dx\\
dv &= \cos x\,dx & v &= \sin x
\end{aligned}
\right|
\right)\\
&= (x^4+3x)\sin x +(4x^3+3)\cos x -12x^2\sin x +24\int x\sin x\,dx\\
&= (x^4+3x)\sin x +(4x^3+3)\cos x -12x^2\sin x +24\left(
\left|
\begin{aligned}
u &= x & du &= dx\\
dv &= \sin x\,dx & v &= -\cos x
\end{aligned}
\right|
\right)\\
&= (x^4+3x)\sin x +(4x^3+3)\cos x -12x^2\sin x -24x\cos x +24\int\cos x\,dx\\
&= (x^4-12x^2+3x+24)\sin x +(4x^3-24x+3)\cos x +C,\ C\in\mathbb{R}.
\end{align*}
$$
</details>
:::

---

:::{.zadatak}
Odredite sljedeće integrale proizvoljnom metodom:

(a) $\displaystyle \int \sin 3x \sin 5x \, dx$

(b) $\displaystyle \int x^2 \sqrt{1-x^2} \, dx$

(c) $\displaystyle \int \sqrt{e^x-1} \, dx$

(d) $\displaystyle \int \frac{6}{7+x^2} \, dx$
:::

:::{.hint}
<details>
<summary>Prikaži hint</summary>
*d.* dio probajte namjestiti na tablični integral.
</details>
:::

:::{.rjesenje}
<details>
<summary>Prikaži rješenje</summary>

(a) Iskoristimo formulu pretvorbe, a zatim direktno integrirajmo:
$$
\begin{align*}
\int \sin 3x \sin 5x\,dx
&= \frac12\int\left(\cos(2x)-\cos(8x)\right)\,dx\\
&= \frac12\left(\int\cos(2x)\,dx-\int\cos(8x)\,dx\right)\\
&= \frac12\left(\frac12\sin(2x)-\frac18\sin(8x)\right)+C\\
&= \frac14\sin(2x)-\frac1{16}\sin(8x)+C,\qquad C\in\mathbb{R}.
\end{align*}
$$

(b) Uvrstimo supstituciju $x = \sin t$ jer ćemo tada pod kroijenom dobiti $\cos ^2 t$:
$$
\begin{align*}
\int x^2\sqrt{1-x^2}\,dx
&=
\left|
\begin{aligned}
x &= \sin t\\
dx &= \cos t\,dt
\end{aligned}
\right|\\
&= \int \sin^2 t\,\cos^2 t\,dt\\
&= \frac14\int\sin^2(2t)\,dt\\
&= \frac14\int\frac{1-\cos(4t)}{2}\,dt\\
&= \frac18\int(1-\cos(4t))\,dt\\
&= \frac{t}{8}-\frac{\sin(4t)}{32}+C.
\end{align*}
$$

gdje smo u četvrtoj jednakosti koristili izraz $\sin ^2 \theta = \dfrac{1 - \cos 2\theta}{2}$.

(c)
$$
\begin{align*}
\int \sqrt{e^x-1}\,dx
&=
\left|
\begin{aligned}
t &= \sqrt{e^x-1}\\
t^2 &= e^x-1\\
2t\,dt &= e^x\,dx=(t^2+1)\,dx
\end{aligned}
\right|\\
&= \int \frac{2t^2}{t^2+1}\,dt\\
&= 2\int\left(1-\frac{1}{t^2+1}\right)\,dt\\
&= 2\left(t-\arctan t\right)+C\\
&= 2\sqrt{e^x-1}-2\arctan\!\left(\sqrt{e^x-1}\right)+C,\qquad C\in\mathbb{R}.
\end{align*}
$$

(d)
$$
\begin{align*}
\int \frac{6}{7+x^2}\,dx
&=
\left|
\begin{aligned}
x &= \sqrt7\tan t\\
dx &= \sqrt7\sec^2 t\,dt
\end{aligned}
\right|\\
&= \int \frac{6\sqrt7\sec^2 t}{7+7\tan^2 t}\,dt\\
&= \frac{6\sqrt7}{7}\int
\frac{\sec^2 t}{1+\tan^2 t}\,dt\\
&= \frac{6\sqrt7}{7}\int dt\\
&= \frac{6\sqrt7}{7}t+C\\
&= \frac{6}{\sqrt7}\arctan\!\left(\frac{x}{\sqrt7}\right)+C,\qquad C\in\mathbb{R}.
\end{align*}
$$

</details>
:::

---

:::{.zadatak}
Neka je $f \colon [−a,a] \to \mathbb{R}$ Riemann integrabilna funkcija.

(a) Ako je $f$ neparna funkcija, dokažite
$$
\int _{-a}^a f(x) \, dx = 0 
$$

(b) Ako je $f$ parna funkcija, dokažite
$$
\int _{-a}^a f(x) \, dx = 2 \int _0^a f(x) \, dx 
$$
:::

:::{.hint}
<details>
<summary>Prikaži hint</summary>
Koristite zamjenu varijabli $t = -x$.
</details>
:::

<!--
:::{.rjesenje}
<details>
<summary>Prikaži rješenje</summary>
(a)
$$
\begin{align*}
\int _{-a}^a f(x)\,dx
&=
\left|
\begin{aligned}
t &= -x & -a &\mapsto a\\
dt &= -dx & a &\mapsto -a
\end{aligned}
\right|\\
&= -\int _{a}^{-a} f(-t) dt \\
&= \int _{-a}^{a} -f(t) dt \\
&= -\int _{-a}^{a} f(t) dt \\
\end{align*}
$$

Izjednačavanjem integrala dobivamo traženu tvrdnju.

Uočite da smo iskoristili činjenicu $\displaystyle -\int _a^b f = \int _b^a f$.

(b)
$$
\begin{align*}
\int _{-a}^a f(x)\,dx
&= \int _{-a}^0 f(x)\,dx + \int _0^a f(x)\,dx \\
&= \left|
\begin{aligned}
t &= -x & -a &\mapsto a\\
dt &= -dx & a &\mapsto -a
\end{aligned}
\right|\\
&= -\int _{a}^0 f(-t)\,dt + \int _0^a f(x)\,dx \\
&= \int _0^{a} f(t)\,dt + \int _0^a f(x)\,dx \\
&= 2 \int _0^x f(x) \, dx
\end{align*}
$$

</details>
:::
-->

---

Za vježbu upućujemo čitatelja na samostalno rješavanje dodatnih zadataka. Neki gore navedeni zadatci koriste  (na prvu) neočekivanu supstituciju, ali osjećaj se za to postiže samostalnim rješavanjem što većeg broja zadataka. 

Postoje vrste integrala za koje je odmah jasno kakvu supstituciju traže, tako primjerice postoje trigonometrijske i hiperboličke supstitucije. Postoje i univerzalne metode za integraciju racionalnih funkcija, kao i (kvadratnih) iracionalnosti. O tim će metoda biti riječ u sljedećim poglavljima.